#
# Funny_en_passant_game = ChessGame()
# Funny_en_passant_game.reset()
# Funny_en_passant_game.move('pawn', "d4")
# Funny_en_passant_game.move("pawn", "d6")
# Funny_en_passant_game.move('queen', 'd4')
# Funny_en_passant_game.move('pawn', 'j4')
# Funny_en_passant_game.move('ostrich', 'e7')
# Funny_en_passant_game.move('king', 'e5')
# Funny_en_passant_game.move('pawn', 'd5')
# Funny_en_passant_game.move('pawn', 'e5')
# Funny_en_passant_game.move('pawn', 'e6')

# Fools_mate = ChessGame()
# Fools_mate.reset()
# Fools_mate.move('pawn', "f3")
# Fools_mate.move("pawn", "e6")
# Fools_mate.move('pawn', 'g4')
# Fools_mate.move('queen', 'h4')

# Open_dfile_game = ChessGame()
# Open_dfile_game.reset()
# Open_dfile_game.move('pawn', "e3")
# Open_dfile_game.move("pawn", "d6")
# Open_dfile_game.move('pawn', 'd4')
# Open_dfile_game.move('pawn', 'e5')
# Open_dfile_game.move('pawn', 'e5')
# Open_dfile_game.move('pawn', 'e5')
# Open_dfile_game.move('queen', 'd8')
# Open_dfile_game.move('pawn', 'a6')
#
# some_Caro_Kann_game = ChessGame()
# some_Caro_Kann_game.move('pawn', 'e4')
# some_Caro_Kann_game.move('pawn', 'c6')
# some_Caro_Kann_game.move('pawn', 'd4')
# some_Caro_Kann_game.move('pawn', 'd5')
# some_Caro_Kann_game.move('pawn', 'e5')
# some_Caro_Kann_game.move('bishop', 'f5')
# some_Caro_Kann_game.move('knight', 'f3')
# some_Caro_Kann_game.move('pawn', 'e6')
# some_Caro_Kann_game.move('bishop', 'd3')
# some_Caro_Kann_game.move('bishop', 'd3')
# some_Caro_Kann_game.move('queen', 'd3')
# some_Caro_Kann_game.move('pawn', 'c5')
# some_Caro_Kann_game.move('pawn', 'c3')
# some_Caro_Kann_game.move('knight', 'c6')
# some_Caro_Kann_game.move('bishop', 'e3')
# some_Caro_Kann_game.move('pawn', 'c4')
# some_Caro_Kann_game.move('queen', 'c2')
# some_Caro_Kann_game.move('knight', 'e7', 'g8')
# some_Caro_Kann_game.move('knight', 'd2', 'b1')
# some_Caro_Kann_game.move('knight', 'g6')
# some_Caro_Kann_game.move('O-O')
# some_Caro_Kann_game.move('bishop', 'e7')
# some_Caro_Kann_game.move('pawn', 'b3')
# some_Caro_Kann_game.move('pawn', 'b3')
# some_Caro_Kann_game.move('pawn', 'b3')
# some_Caro_Kann_game.move('O-O')
# some_Caro_Kann_game.move('pawn', 'c4')
# some_Caro_Kann_game.move('pawn', 'c4')
# some_Caro_Kann_game.move('pawn', 'c4')
# some_Caro_Kann_game.move('rook', 'c8')
# some_Caro_Kann_game.move('knight', 'b3')
# some_Caro_Kann_game.move('pawn', 'b6')
# some_Caro_Kann_game.move('rook', 'd1', 'f1')
# some_Caro_Kann_game.move('knight', 'b4')
# some_Caro_Kann_game.move('queen', 'c3')
# some_Caro_Kann_game.move('pawn', 'h6')
# some_Caro_Kann_game.move('rook', 'a7')
# some_Caro_Kann_game.move('knight', 'c6')
# some_Caro_Kann_game.move('rook', 'a6')
# some_Caro_Kann_game.move('pawn', 'b5')
# some_Caro_Kann_game.move('pawn', 'c5')
# some_Caro_Kann_game.move('queen', 'd7')
# some_Caro_Kann_game.move('rook', 'a1', 'd1')
# some_Caro_Kann_game.move('pawn', 'f5')
# some_Caro_Kann_game.move('knight', 'a5')
# some_Caro_Kann_game.move('knight', 'a5')
# some_Caro_Kann_game.move('queen', 'a5')
# some_Caro_Kann_game.move('pawn', 'f4')
# some_Caro_Kann_game.move('bishop', 'd2')
# some_Caro_Kann_game.move('knight', 'h4')
# some_Caro_Kann_game.move('knight', 'h4')
# some_Caro_Kann_game.move('bishop', 'h4')
# some_Caro_Kann_game.move('rook', 'b6')
# some_Caro_Kann_game.move('pawn', 'f3')
# some_Caro_Kann_game.move('pawn', 'g3')
# some_Caro_Kann_game.move('bishop', 'g5')
# some_Caro_Kann_game.move('bishop', 'c3')
# some_Caro_Kann_game.move('bishop', 'e3')
# some_Caro_Kann_game.move('pawn', 'e3')
# some_Caro_Kann_game.move('pawn', 'f2')
# some_Caro_Kann_game.move('king', 'f1')
# some_Caro_Kann_game.move('queen', 'f7')
# some_Caro_Kann_game.move('queen', 'b5')
# some_Caro_Kann_game.move('queen', 'f3')
# some_Caro_Kann_game.resign()